version: 0.1
phases:
  install:
    commands:
      - pip install --upgrade --user awscli
      - cd src; pip install porper -t ./lib; cd ..
  build:
    commands:
      - sed -i "s/AWS::REGION/$AWS_DEFAULT_REGION/g" swagger.yaml
      - sed -i "s/AWS::ACCOUNT_ID/$AWS_ACCOUNT_ID/g" swagger.yaml
      - aws cloudformation package
         --template-file template.yaml
         --s3-bucket $S3_BUCKET_NAME
         --output-template-file samTemplate.yaml
  post_build:
    commands:
      - chmod a+x s3.sh
      - ./s3.sh
artifacts:
  type: zip
  files:
    - samTemplate.yaml
