AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Parameters:
  GoogleTokeninfoEndpoint:
    Type: String
    Default: "https://www.googleapis.com/oauth2/v3/tokeninfo?id_token="
    Description: Endpoint url to confirm Google tokens
  SsoHost:
    Type: String
    Default: ""
    Description: SSO Host Name
  SsoUser:
    Type: String
    Default: ""
    Description: SSO User Name
  SsoPassword:
    Type: String
    Default: ""
    NoEcho: true
    Description: SSO Password
  SsoRedirectUri:
    Type: String
    Default: ""
    Description: SSO Redirect Url
  GithubAuthEndpoint:
    Type: String
    Default: "https://github.com/login/oauth"
    Description: Endpoint url to confirm GitHub tokens
  GithubApiEndpoint:
    Type: String
    Default: "https://api.github.com"
    Description: GitHub API Endpoint url
  GithubClientId:
    Type: String
    Default: ""
    Description: GitHub Client Id
  GithubClientSecret:
    Type: String
    NoEcho: true
    Default: ""
    Description: GitHub Client Secret
  GithubRedirectUri:
    Type: String
    NoEcho: true
    Default: ""
    Description: GitHub Redirect Uri
  ReadCapacityUnit:
    Description: Read Capacity Unit for DynamoDB Tables
    Type: Number
    Default: 5
  WriteCapacityUnit:
    Description: Write Capacity Unit for DynamoDB Tables
    Type: Number
    Default: 5
Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName : "users"
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnit
        WriteCapacityUnits: !Ref WriteCapacityUnit
  GroupTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName : "groups"
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnit
        WriteCapacityUnits: !Ref WriteCapacityUnit
  AccessTokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName : "access_tokens"
      AttributeDefinitions:
        -
          AttributeName: "access_token"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "access_token"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnit
        WriteCapacityUnits: !Ref WriteCapacityUnit
  PermissionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName : "permissions"
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnit
        WriteCapacityUnits: !Ref WriteCapacityUnit
  InvitedUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName : "invited_users"
      AttributeDefinitions:
        -
          AttributeName: "email"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "email"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnit
        WriteCapacityUnits: !Ref WriteCapacityUnit
  UserGroupTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName : "user_group_rels"
      AttributeDefinitions:
        -
          AttributeName: "user_id"
          AttributeType: "S"
        -
          AttributeName: "group_id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "user_id"
          KeyType: "HASH"
        -
          AttributeName: "group_id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnit
        WriteCapacityUnits: !Ref WriteCapacityUnit
  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName : "orders"
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnit
        WriteCapacityUnits: !Ref WriteCapacityUnit
  EncryptionDecryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Encryption and Decryption key for Lambda"
      KeyPolicy:
        Id: "LambdaEncDec"
        Version: "2012-10-17"
        Statement:
          -
            Sid: "Allow administration of the key"
            Effect: "Allow"
            Action:
              - "kms:*"
            Principal:
              AWS: !Ref AWS::AccountId
            Resource: '*'
          -
            Sid: "Allow Encryption Service to use this key"
            Effect: "Allow"
            Action:
              - "kms:Encrypt"
            Principal:
              AWS: !GetAtt LambdaFunctionIAMRole.Arn
            Resource: '*'
          -
            Sid: "Allow Decryption Service to use this key"
            Effect: "Allow"
            Action:
              - "kms:Decrypt"
            Principal:
              AWS: !GetAtt LambdaFunctionIAMRole.Arn
            Resource: '*'
  LambdaFunctionIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "AllowLambdaServiceToAssumeRole"
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        -
          PolicyName: "InlinePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "dynamodb:DeleteItem"
                  - "dynamodb:GetItem"
                  - "dynamodb:BatchGetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:Query"
                  - "dynamodb:Scan"
                  - "dynamodb:UpdateItem"
                  - "kms:Encrypt"
                  - "kms:Decrypt"
                Resource: "*"
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./swagger.yaml
      StageName: Prod
      Variables:
        LambdaFunctionName: !Ref ProxyFunction
  ProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SungardAS-Porper-Proxy
      Handler: api_handler.lambda_handler
      Runtime: python2.7
      CodeUri: ./src
      Role: !GetAtt LambdaFunctionIAMRole.Arn
      Timeout: 300
      Environment:
        Variables:
          GOOGLE_TOKENINFO_ENDPOINT: !Ref GoogleTokeninfoEndpoint
          SSO_HOST: !Ref SsoHost
          SSO_USER: !Ref SsoUser
          SSO_PASSWORD: !Ref SsoPassword
          SSO_REDIRECT_URI: !Ref SsoRedirectUri
          GITHUB_AUTH_ENDPOINT: !Ref GithubAuthEndpoint
          GITHUB_API_ENDPOINT: !Ref GithubApiEndpoint
          GITHUB_CLIENT_ID: !Ref GithubClientId
          GITHUB_CLIENT_SECRET: !Ref GithubClientSecret
          GITHUB_REDIRECT_URI: !Ref GithubRedirectUri
          KMS_REGION: !Ref 'AWS::Region'
          KMS_KEY_ID: !Ref EncryptionDecryptionKey
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /{proxy+}
            Method: ANY
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SungardAS-Porper
      Handler: handler.lambda_handler
      Runtime: python2.7
      CodeUri: ./src
      Role: !GetAtt LambdaFunctionIAMRole.Arn
      Timeout: 300
      Environment:
        Variables:
          GOOGLE_TOKENINFO_ENDPOINT: !Ref GoogleTokeninfoEndpoint
          SSO_HOST: !Ref SsoHost
          SSO_USER: !Ref SsoUser
          SSO_PASSWORD: !Ref SsoPassword
          SSO_REDIRECT_URI: !Ref SsoRedirectUri
          GITHUB_AUTH_ENDPOINT: !Ref GithubAuthEndpoint
          GITHUB_API_ENDPOINT: !Ref GithubApiEndpoint
          GITHUB_CLIENT_ID: !Ref GithubClientId
          GITHUB_CLIENT_SECRET: !Ref GithubClientSecret
          GITHUB_REDIRECT_URI: !Ref GithubRedirectUri
          KMS_REGION: !Ref 'AWS::Region'
          KMS_KEY_ID: !Ref EncryptionDecryptionKey
Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref ApiGatewayApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/Prod'
  ProxyLambdaFunctionArn:
    Description: "Proxy Lambda Function ARN"
    Value: !GetAtt ProxyFunction.Arn
  LambdaFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt LambdaFunction.Arn
